name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  
jobs:
  test:
    # Only run this job if the push is to the main branch (no PRs)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Build
    permissions:
      contents: read
    runs-on: self-hosted

    steps:

    - name: checkout code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2

    - name: capture version
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: setup gcloud
      uses: google-github-actions/setup-gcloud@e30db14379863a8c79331b04a9969f4c1e225e0b  # v1.1.1

    - name: auth to registry
      run: |-
        gcloud auth configure-docker

    - name: Define Metadata
      id: meta
      uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175  # v4.6.0
      with:
        images: |
          us-docker.pkg.dev/s3cme1/grunner/simple
        tags: |
          "v${GITHUB_RUN_NUMBER}"

    - name: Push Image
      id: push
      uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825  # v4.1.1
      with:
        file: samples/Dockerfile.simple
        push: true
        tags: ${{ steps.meta.outputs.tags }}